# Generated by Django 4.2.1 on 2023-06-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payload',
            options={'ordering': ['-created_at']},
        ),
    ]
