# Generated by Django 4.2.1 on 2023-06-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_alter_payload_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payload',
            options={},
        ),
        migrations.RemoveField(
            model_name='payload',
            name='created_at',
        ),
    ]
